### ISSUE TITLE
BaseAvroRecord is not exported in 2.2.0 package

### ISSUE THREAD

**Issue by rurutia** [bornfight/avro-to-typescript#24]
In 2.2.0 package, 
> export * from "./components/Avro/BaseAvroRecord";

is missing from **/dist/src/index.d.ts**

this causes **BaseAvroRecord.ts** generated in output folder broken hence all classes extending it

> export { BaseAvroRecord } from "@degordian/avro-to-typescript";

**Comment by dvorsky** [comment]
Hi, thanks for noticing. I patched the release and it should work fine now, please upgrade to 2.2.1 version.
