### ISSUE TITLE
Version 3.2.2 Typescript error with defined classRow

### ISSUE THREAD

**Issue by rhammonds1** [bornfight/avro-to-typescript#29]
The below is valid AVRO. 
`{
    "type": "record",
    "name": "AlbumCreatedEvent",
    "namespace": "com.sporkify.dcp.event.schema.krandorify",
    "doc": "Information about the Song Added event",
    "fields": [{
        "name": "eventHeader",
        "type": {
            "type": "record",
            "name": "EventHeader",
            "namespace": "com.sporkify.commons.krandorify",
            "fields": [{
                "name": "id",
                "type": "string"
            }, {
                "name": "time",
                "type": {
                    "type": "long",
                    "logicalType": "timestamp-millis"
                }
            }, {
                "name": "type",
                "type": "string"
            }, {
                "name": "source",
                "type": "string"
            }]
        }
    }, {
        "name": "albumName",
        "type": ["null", "string"],
        "default": null
    }, {
        "name": "songList",
        "type": ["null", {
            "type": "array",
            "items": {
                "type": "record",
                "name": "Song",
                "namespace": "com.sporkify.commons.krandorify",
                "fields": [{
                    "name": "title",
                    "type": "string",
                    "doc": "Title of the Song"
                }, {
                    "name": "artist",
                    "type": "string",
                    "doc": "The song composer"
                }, {
                    "name": "duration",
                    "type": "int",
                    "doc": "Song Duration in minutes"
                }, {
                    "name": "bitrate",
                    "type": "int",
                    "doc": "Song Bitrate, measured in kilobytes per second"
                }, {
                    "name": "lyrics",
                    "type": "string",
                    "doc": "Lyrics of the Song"
                }, {
                    "name": "fileURL",
                    "type": "string",
                    "doc": "Unique file Reference to the song"
                }, {
                    "name": "demo_two",
                    "type": "string",
                    "doc": "Demoing a thing",
                    "default": "Doing awesome"
                }]
            }
        }]
    }],
    "version": "2"
}`

We are expecting that an EventHeader and Song are passed into the event every time. When I compile the schema into Typescript I receive an error on the classRow indicating:

"Property 'song' has no initializer and is not definitely assigned in the constructor". 

This can be resolved by changing the classRow definition

From:
`
    public eventHeader: EventHeader;
    public song: Song;
`

To:
`
    public eventHeader!: EventHeader;
    public song!: Song;
`

I have fixed this locally. If you agree this is the correct solution I will submit a PR.

Thanks!

**Comment by dvorsky** [comment]
I see, we did not run into this problem since we had "strictPropertyInitialization" set to false. As such, it should be okay to insert "!" operator, but it should only be placed if property is not possibly undefined or explicitly initialised. Do you agree?

**Comment by rhammonds1** [comment]
The change I made only inserted the ! when the field was not optional and it did not have a default value. I will submit a PR.

Thanks for you the turn around.

**Comment by rhammonds1** [comment]
I also made a change to provide a top level index.ts that exports all of the generated Typescript class files. This made creating a publishable package much easier. Would this be something you would want in the library? If so, I'll create another issue and submit another PR.

Thanks!

**Comment by dvorsky** [comment]
Hey, sorry for not replying sooner! If the change only handles the "not-optional, no-default" properties then great! Will review it and merge if everything is alright.

About the exports, what was missing from the current index.ts? I tried only exporting what I though was necessary for the end usage of package, but I'm open to exporting everything if you think it's useful

**Comment by rhammonds1** [comment]
Sorry I meant a generated index.ts that would export the generated
typescript classes. That allows a user to add a package.json to the output
directory and it can be bundled for publishing. The generated index.ts
sites next to the BaseAvroRecord.
